### ISSUE TITLE
when load error class="lazyerror" not exists.

### ISSUE THREAD

**Issue by tenfei4** [kuarz-dev/nuxt-lazyimages#1]
**css code.**
```
img.lazypreload,img.lazyloading,img.lazyload{content: url("/imageLoading.svg");object-fit: none; object-position: center;}
img.lazyerror{content: url("/imageError.svg");object-fit: none; object-position: center;}
```
lazyerror not exists. how to use is?

**Comment by VicFleur** [comment]
Closing for now as the original library doesn't actually listen for errors on the image (see [this Issue](https://github.com/aFarkas/lazysizes/issues/615)) despite having an ```errorClass``` definition (which was copied as is for this library configuration). I might consider adding a small function for that since I'm embedding the original library anyway
